name: otter
description: "Flutter plugin designed to simplify the management of HTTP requests in offline and online modes."
version: 1.0.2
homepage: https://nexhub.fr/
repository: https://github.com/NexhubFR/otter

environment:
  sdk: '3.3.3'
  flutter: '>=3.19.5'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  path: ^1.9.0
  uuid: ^4.3.3
  sembast: ^3.7.1
  path_provider: ^2.1.2
  synchronized: ^3.1.0+1
  connectivity_plus: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
