name: push-on-develop
on: 
  push: 
    branches:
      - develop

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
            build-command: "cd example && flutter build apk"
          - platform: ios
            os: macos-latest
            build-command: "cd example && flutter build ios --no-codesign"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.5'
      - run: flutter --version
      - uses: actions/checkout@v4
      - run: ${{ matrix.build-command }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.5'
      - run: flutter --version
      - uses: actions/checkout@v4
      - run: flutter test
